# Generated by Django 4.0.6 on 2022-07-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='sin titulo', max_length=255),
        ),
    ]
